server:
  port: 8999
  address: 0.0.0.0

spring:
   main:
     allow-bean-definition-overriding: true
   profiles:
     active: dev
   redis:
     host: localhost
     password: 123456
     port: 6379
     Lettuce:
       pool :
          max-wait: 100


soul :
    filterTimeEnable : false
    filterTime : 10
    sync:
        strategy: websocket
        websocket :
             url: ws://localhost:8887/websocket
#        zookeeper:
#             url: localhost:2181
#             sessionTimeout: 5000
#             connectionTimeout: 2000
#        http:
#             url : localhost:8888

logging:
    level:
        root: info
        org.springframework.boot: info
        org.apache.ibatis: info
        org.dromara.soul.bonuspoint: info
        org.dromara.soul.lottery: debug
        org.dromara.soul: debug

    path: "./logs"
